/**
 * Example: Pairs Trading Strategy Demo with SPY/QQQ
 * 
 * This example demonstrates the pairs trading strategy interface with real
 * market data. It shows the signal generation logic without running a full
 * backtest, making it useful for understanding how the strategy works.
 * 
 * The pairs trading strategy trades the spread between two correlated assets:
 * - When spread deviates significantly below mean → BUY Asset A, SELL Asset B
 * - When spread deviates significantly above mean → SELL Asset A, BUY Asset B
 * - When spread reverts to mean → Close positions
 * 
 * This demo reads the first 100 periods from SPY and QQQ CSV files and
 * displays the trading signals generated by the strategy.
 * 
 * Usage:
 *   ./examples/backtest/pairs_demo tests/data/spy.csv tests/data/qqq.csv
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "wu.h"

int main(int argc, char* argv[]) {
    if (argc < 3) {
        fprintf(stderr, "Usage: %s <spy.csv> <qqq.csv>\n", argv[0]);
        fprintf(stderr, "Example: %s tests/data/spy.csv tests/data/qqq.csv\n", argv[0]);
        return 1;
    }
    
    // Open CSV files
    FILE* spy_file = fopen(argv[1], "r");
    FILE* qqq_file = fopen(argv[2], "r");
    
    if (!spy_file || !qqq_file) {
        fprintf(stderr, "Error: Could not open CSV files\n");
        if (spy_file) fclose(spy_file);
        if (qqq_file) fclose(qqq_file);
        return 1;
    }
    
    // Create CSV readers for both assets
    WU_Reader spy_reader = (WU_Reader)wu_csv_reader_new(spy_file, WU_DATA_TYPE_CANDLE, true);
    WU_Reader qqq_reader = (WU_Reader)wu_csv_reader_new(qqq_file, WU_DATA_TYPE_CANDLE, true);
    
    if (!spy_reader || !qqq_reader) {
        fprintf(stderr, "Error: Could not create CSV readers\n");
        fclose(spy_file);
        fclose(qqq_file);
        return 1;
    }
    
    // Create a pairs trading strategy
    // Parameters:
    //   window = 20 periods (lookback for spread statistics)
    //   threshold = 2.0 standard deviations (entry/exit bands)
    //   ratio = 1.0 (1:1 hedge ratio for simplicity)
    WU_Strategy strategy = (WU_Strategy)wu_pairs_trading_strat_new(20, 2.0, 1.0);
    
    printf("=== Pairs Trading Strategy Demo: SPY vs QQQ ===\n");
    printf("Strategy Configuration:\n");
    printf("  Window: 20 periods\n");
    printf("  Threshold: 2.0 standard deviations\n");
    printf("  Number of inputs: %d (SPY, QQQ)\n", strategy->num_inputs);
    printf("  Number of outputs: %d (one signal per asset)\n\n", strategy->num_outputs);
    
    printf("Trading Signals (first 100 periods):\n");
    printf("%-6s %-10s %-10s %-10s %-10s %-10s %-10s\n", 
           "Period", "SPY", "QQQ", "Spread", "SPY_Signal", "QQQ_Signal", "Logic");
    printf("--------------------------------------------------------------------------------\n");
    
    int period = 0;
    const int max_periods = 100;
    
    void* spy_data;
    void* qqq_data;
    
    while (period < max_periods &&
           (spy_data = wu_reader_next(spy_reader)) != NULL &&
           (qqq_data = wu_reader_next(qqq_reader)) != NULL) {
        
        WU_Candle* spy_candle = (WU_Candle*)spy_data;
        WU_Candle* qqq_candle = (WU_Candle*)qqq_data;
        
        // Use closing prices
        WU_Single spy_close = wu_single_init(spy_candle->timestamp, spy_candle->close);
        WU_Single qqq_close = wu_single_init(qqq_candle->timestamp, qqq_candle->close);
        
        // Prepare input array
        const void* inputs[2] = {&spy_close, &qqq_close};
        
        // Update strategy with both inputs - returns pointer to 2 signals
        WU_Signal* signals = wu_strategy_update(strategy, inputs);
        
        // Calculate spread for display
        double spread = spy_candle->close - qqq_candle->close;
        
        // Get signal strings (strategy always returns 2 signals for pairs trading)
        const char* spy_signal = (signals[0].side == WU_SIDE_BUY) ? "BUY" :
                                 (signals[0].side == WU_SIDE_SELL) ? "SELL" : "HOLD";
        
        const char* qqq_signal = (signals[1].side == WU_SIDE_BUY) ? "BUY" :
                                 (signals[1].side == WU_SIDE_SELL) ? "SELL" : "HOLD";
        
        const char* logic = "";
        
        // Explain the logic
        if (strcmp(spy_signal, "BUY") == 0 && strcmp(qqq_signal, "SELL") == 0) {
            logic = "Spread low→Long";
        } else if (strcmp(spy_signal, "SELL") == 0 && strcmp(qqq_signal, "BUY") == 0) {
            logic = "Spread high→Short";
        } else if (strcmp(spy_signal, "SELL") == 0 && strcmp(qqq_signal, "SELL") == 0) {
            logic = "Exit long";
        } else if (strcmp(spy_signal, "BUY") == 0 && strcmp(qqq_signal, "BUY") == 0) {
            logic = "Exit short";
        }
        
        printf("%-6d %-10.2f %-10.2f %-10.2f %-10s %-10s %-10s\n",
               period, spy_candle->close, qqq_candle->close, spread,
               spy_signal, qqq_signal, logic);
        
        period++;
    }
    
    printf("\n=== Strategy Logic Explanation ===\n");
    printf("The pairs trading strategy monitors the spread (SPY - QQQ) and:\n\n");
    printf("1. ENTRY SIGNALS:\n");
    printf("   - When spread < mean - 2*stddev (SPY undervalued relative to QQQ)\n");
    printf("     → BUY SPY + SELL QQQ (bet on mean reversion)\n");
    printf("   - When spread > mean + 2*stddev (SPY overvalued relative to QQQ)\n");
    printf("     → SELL SPY + BUY QQQ (bet on mean reversion)\n\n");
    printf("2. EXIT SIGNALS:\n");
    printf("   - When spread crosses back through the mean\n");
    printf("     → Close both positions (mean reversion achieved)\n\n");
    printf("3. KEY FEATURES:\n");
    printf("   - Market neutral (long one asset, short the other)\n");
    printf("   - Profits from relative price movements, not market direction\n");
    printf("   - Uses statistical mean reversion\n");
    
    // Cleanup
    wu_reader_delete(spy_reader);
    wu_reader_delete(qqq_reader);
    wu_strategy_delete(strategy);
    
    return 0;
}
