#ifndef WU_TYPES_H
#define WU_TYPES_H

#include <stdint.h>
#include <stdbool.h>

/**
 * Side represents the direction of a signal or a trade.
 */
typedef enum {
    SIDE_HOLD = 0,
    SIDE_BUY = 1,
    SIDE_SELL = 2
} Side;

/**
 * DataType represents the type of input data, which can be a candle, a
 * trade, or a single value. All these types include a timestamp field
 * to represent Unix times. The time scale is not fixed and can be
 * determined by the user, e.g., it can be in seconds, milliseconds, or
 * nanoseconds.
 */
typedef enum {
    DATA_TYPE_CANDLE = 0,
    DATA_TYPE_TRADE = 1,
    DATA_TYPE_SINGLE_VALUE = 2
} DataType;

/**
 * Signal represents a trading signal generated by a strategy. It
 * includes a timestamp, a side (buy, sell, or hold), a price at which
 * to execute the trade, and a quantity to trade. Not all fields may
 * be relevant for every signal, e.g., a hold signal may not require a
 * price or quantity.
 */
typedef struct {
    int64_t timestamp;
    Side side;
    double price;
    double quantity;
} Signal;

/**
 * TimeUnit represents a unit of time used for time-based calculations
 * such as time-weighted returns or time-based aggregations.
 */
typedef enum {
    SECOND = 0,
    MINUTE = 1,
    HOUR = 2,
    DAY = 3,
    WEEK = 4,
    MONTH = 8,
    YEAR = 9
} TimeUnit;

/**
 * CloseReason represents the reason for closing a position, which can
 * be a trading signal, a stop loss, or a take profit. This enum is used
 * to categorize the trades in the portfolio statistics, allowing for
 * analysis of the performance of the strategy based on different exit
 * reasons.
 */
typedef enum {
    CLOSE_REASON_SIGNAL = 0,
    CLOSE_REASON_STOP_LOSS = 1,
    CLOSE_REASON_TAKE_PROFIT = 2
} CloseReason;

/**
 * PositionSizeType represents the type of position sizing used in the
 * portfolio, which can be absolute or percentage-based.
 */
typedef enum PositionSizeType {
    POSITION_SIZE_ABS = 0,
    POSITION_SIZE_PCT = 1
} PositionSizeType;

#endif // WU_TYPES_H
