#ifndef WU_TYPES_H
#define WU_TYPES_H

#include <stdint.h>
#include <stdbool.h>

/**
 * WU_Side represents the direction of a signal or a trade.
 */
typedef enum {
    WU_SIDE_HOLD = 0,
    WU_SIDE_BUY = 1,
    WU_SIDE_SELL = 2
} WU_Side;

/**
 * WU_DataType represents the type of input data, which can be a candle, a
 * trade, or a single value. All these types include a timestamp field
 * to represent Unix times. The time scale is not fixed and can be
 * determined by the user, e.g., it can be in seconds, milliseconds, or
 * nanoseconds.
 */
typedef enum {
    WU_DATA_TYPE_CANDLE = 0,
    WU_DATA_TYPE_TRADE = 1,
    WU_DATA_TYPE_SINGLE_VALUE = 2
} WU_DataType;

/**
 * WU_Signal represents a trading signal generated by a strategy. It
 * includes a timestamp, a side (buy, sell, or hold), a price at which
 * to execute the trade, and a quantity to trade.
 * 
 * For multi-asset strategies, the position of the signal in the returned
 * array indicates which asset it applies to (0-based index).
 */
typedef struct {
    int64_t timestamp;
    WU_Side side;
    double price;
    double quantity;
} WU_Signal;

/**
 * WU_TimeUnit represents a unit of time used for time-based calculations
 * such as time-weighted returns or time-based aggregations.
 */
typedef enum {
    WU_SECOND = 0,
    WU_MINUTE = 1,
    WU_HOUR = 2,
    WU_DAY = 3,
    WU_WEEK = 4,
    WU_MONTH = 8,
    WU_YEAR = 9
} WU_TimeUnit;

/**
 * WU_CloseReason represents the reason for closing a position, which can
 * be a trading signal, a stop loss, or a take profit. This enum is used
 * to categorize the trades in the portfolio statistics, allowing for
 * analysis of the performance of the strategy based on different exit
 * reasons.
 */
typedef enum {
    WU_CLOSE_REASON_SIGNAL = 0,
    WU_CLOSE_REASON_STOP_LOSS = 1,
    WU_CLOSE_REASON_TAKE_PROFIT = 2
} WU_CloseReason;

#define wu_symbol_list(...) ((const char*[]){__VA_ARGS__, NULL})

#endif // WU_TYPES_H
