# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _wu
else:
    import _wu

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def new_doubleArray(nelements):
    return _wu.new_doubleArray(nelements)

def delete_doubleArray(ary):
    return _wu.delete_doubleArray(ary)

def doubleArray_getitem(ary, index):
    return _wu.doubleArray_getitem(ary, index)

def doubleArray_setitem(ary, index, value):
    return _wu.doubleArray_setitem(ary, index, value)
SIDE_HOLD = _wu.SIDE_HOLD
SIDE_BUY = _wu.SIDE_BUY
SIDE_SELL = _wu.SIDE_SELL
DATA_TYPE_CANDLE = _wu.DATA_TYPE_CANDLE
DATA_TYPE_TRADE = _wu.DATA_TYPE_TRADE
DATA_TYPE_SINGLE_VALUE = _wu.DATA_TYPE_SINGLE_VALUE
class Signal(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    timestamp = property(_wu.Signal_timestamp_get, _wu.Signal_timestamp_set)
    side = property(_wu.Signal_side_get, _wu.Signal_side_set)
    price = property(_wu.Signal_price_get, _wu.Signal_price_set)
    quantity = property(_wu.Signal_quantity_get, _wu.Signal_quantity_set)

    def __init__(self):
        _wu.Signal_swiginit(self, _wu.new_Signal())
    __swig_destroy__ = _wu.delete_Signal

# Register Signal in _wu:
_wu.Signal_swigregister(Signal)
SECOND = _wu.SECOND
MINUTE = _wu.MINUTE
HOUR = _wu.HOUR
DAY = _wu.DAY
WEEK = _wu.WEEK
MONTH = _wu.MONTH
YEAR = _wu.YEAR
CLOSE_REASON_SIGNAL = _wu.CLOSE_REASON_SIGNAL
CLOSE_REASON_STOP_LOSS = _wu.CLOSE_REASON_STOP_LOSS
CLOSE_REASON_TAKE_PROFIT = _wu.CLOSE_REASON_TAKE_PROFIT
POSITION_SIZE_ABS = _wu.POSITION_SIZE_ABS
POSITION_SIZE_PCT = _wu.POSITION_SIZE_PCT
class Candle(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    timestamp = property(_wu.Candle_timestamp_get, _wu.Candle_timestamp_set)
    open = property(_wu.Candle_open_get, _wu.Candle_open_set)
    high = property(_wu.Candle_high_get, _wu.Candle_high_set)
    low = property(_wu.Candle_low_get, _wu.Candle_low_set)
    close = property(_wu.Candle_close_get, _wu.Candle_close_set)
    volume = property(_wu.Candle_volume_get, _wu.Candle_volume_set)
    data_type = property(_wu.Candle_data_type_get, _wu.Candle_data_type_set)

    def __init__(self):
        _wu.Candle_swiginit(self, _wu.new_Candle())
    __swig_destroy__ = _wu.delete_Candle

# Register Candle in _wu:
_wu.Candle_swigregister(Candle)
class Trade(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    timestamp = property(_wu.Trade_timestamp_get, _wu.Trade_timestamp_set)
    price = property(_wu.Trade_price_get, _wu.Trade_price_set)
    volume = property(_wu.Trade_volume_get, _wu.Trade_volume_set)
    side = property(_wu.Trade_side_get, _wu.Trade_side_set)
    data_type = property(_wu.Trade_data_type_get, _wu.Trade_data_type_set)

    def __init__(self):
        _wu.Trade_swiginit(self, _wu.new_Trade())
    __swig_destroy__ = _wu.delete_Trade

# Register Trade in _wu:
_wu.Trade_swigregister(Trade)
class SingleValue(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    timestamp = property(_wu.SingleValue_timestamp_get, _wu.SingleValue_timestamp_set)
    value = property(_wu.SingleValue_value_get, _wu.SingleValue_value_set)
    data_type = property(_wu.SingleValue_data_type_get, _wu.SingleValue_data_type_set)

    def __init__(self):
        _wu.SingleValue_swiginit(self, _wu.new_SingleValue())
    __swig_destroy__ = _wu.delete_SingleValue

# Register SingleValue in _wu:
_wu.SingleValue_swigregister(SingleValue)

def candle_init(timestamp, open, high, low, close, volume):
    return _wu.candle_init(timestamp, open, high, low, close, volume)

def trade_init(timestamp, price, volume, side):
    return _wu.trade_init(timestamp, price, volume, side)

def single_value_init(timestamp, value):
    return _wu.single_value_init(timestamp, value)

def signal_init(timestamp, side, price, quantity):
    return _wu.signal_init(timestamp, side, price, quantity)
class Indicator_(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    update = property(_wu.Indicator__update_get, _wu.Indicator__update_set)
    value = property(_wu.Indicator__value_get, _wu.Indicator__value_set)
    delete = property(_wu.Indicator__delete_get, _wu.Indicator__delete_set)

    def __init__(self):
        _wu.Indicator__swiginit(self, _wu.new_Indicator_())
    __swig_destroy__ = _wu.delete_Indicator_

# Register Indicator_ in _wu:
_wu.Indicator__swigregister(Indicator_)
class MovingAverage_(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    base = property(_wu.MovingAverage__base_get, _wu.MovingAverage__base_set)
    prev_values = property(_wu.MovingAverage__prev_values_get, _wu.MovingAverage__prev_values_set)
    window_size = property(_wu.MovingAverage__window_size_get, _wu.MovingAverage__window_size_set)
    pos = property(_wu.MovingAverage__pos_get, _wu.MovingAverage__pos_set)
    len = property(_wu.MovingAverage__len_get, _wu.MovingAverage__len_set)
    sum = property(_wu.MovingAverage__sum_get, _wu.MovingAverage__sum_set)

    def update(self, value):
        return _wu.MovingAverage__update(self, value)

    def value(self):
        return _wu.MovingAverage__value(self)
    __swig_destroy__ = _wu.delete_MovingAverage_

    def __init__(self):
        _wu.MovingAverage__swiginit(self, _wu.new_MovingAverage_())

# Register MovingAverage_ in _wu:
_wu.MovingAverage__swigregister(MovingAverage_)

def moving_average_new(window_size):
    return _wu.moving_average_new(window_size)
class ExponentialMovingAverage_(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    base = property(_wu.ExponentialMovingAverage__base_get, _wu.ExponentialMovingAverage__base_set)
    prev_value = property(_wu.ExponentialMovingAverage__prev_value_get, _wu.ExponentialMovingAverage__prev_value_set)
    alpha = property(_wu.ExponentialMovingAverage__alpha_get, _wu.ExponentialMovingAverage__alpha_set)
    len = property(_wu.ExponentialMovingAverage__len_get, _wu.ExponentialMovingAverage__len_set)
    period = property(_wu.ExponentialMovingAverage__period_get, _wu.ExponentialMovingAverage__period_set)

    def update(self, value):
        return _wu.ExponentialMovingAverage__update(self, value)

    def value(self):
        return _wu.ExponentialMovingAverage__value(self)
    __swig_destroy__ = _wu.delete_ExponentialMovingAverage_

    def __init__(self):
        _wu.ExponentialMovingAverage__swiginit(self, _wu.new_ExponentialMovingAverage_())

# Register ExponentialMovingAverage_ in _wu:
_wu.ExponentialMovingAverage__swigregister(ExponentialMovingAverage_)

def exponential_moving_average_new(period, smoothing):
    return _wu.exponential_moving_average_new(period, smoothing)
class Reader_(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    next = property(_wu.Reader__next_get, _wu.Reader__next_set)
    delete = property(_wu.Reader__delete_get, _wu.Reader__delete_set)

    def __init__(self):
        _wu.Reader__swiginit(self, _wu.new_Reader_())
    __swig_destroy__ = _wu.delete_Reader_

# Register Reader_ in _wu:
_wu.Reader__swigregister(Reader_)
CSV_MAX_LINE_SIZE = _wu.CSV_MAX_LINE_SIZE
CSV_OK = _wu.CSV_OK
CSV_ERROR_EOF = _wu.CSV_ERROR_EOF
CSV_ERROR_PARSE = _wu.CSV_ERROR_PARSE
class CsvReader_(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    base = property(_wu.CsvReader__base_get, _wu.CsvReader__base_set)
    file = property(_wu.CsvReader__file_get, _wu.CsvReader__file_set)
    line_buffer = property(_wu.CsvReader__line_buffer_get, _wu.CsvReader__line_buffer_set)
    has_headers = property(_wu.CsvReader__has_headers_get, _wu.CsvReader__has_headers_set)
    data_type = property(_wu.CsvReader__data_type_get, _wu.CsvReader__data_type_set)
    last_error = property(_wu.CsvReader__last_error_get, _wu.CsvReader__last_error_set)
    data = property(_wu.CsvReader__data_get)

    def next(self):
        return _wu.CsvReader__next(self)

    def get_last_error(self):
        return _wu.CsvReader__get_last_error(self)

    def read_candle(self):
        return _wu.CsvReader__read_candle(self)

    def read_trade(self):
        return _wu.CsvReader__read_trade(self)

    def read_single_value(self):
        return _wu.CsvReader__read_single_value(self)
    __swig_destroy__ = _wu.delete_CsvReader_

    def __init__(self):
        _wu.CsvReader__swiginit(self, _wu.new_CsvReader_())

# Register CsvReader_ in _wu:
_wu.CsvReader__swigregister(CsvReader_)
class CsvReader__data(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    candle = property(_wu.CsvReader__data_candle_get, _wu.CsvReader__data_candle_set)
    trade = property(_wu.CsvReader__data_trade_get, _wu.CsvReader__data_trade_set)
    single_value = property(_wu.CsvReader__data_single_value_get, _wu.CsvReader__data_single_value_set)

    def __init__(self):
        _wu.CsvReader__data_swiginit(self, _wu.new_CsvReader__data())
    __swig_destroy__ = _wu.delete_CsvReader__data

# Register CsvReader__data in _wu:
_wu.CsvReader__data_swigregister(CsvReader__data)

def csv_reader_new(file, data_type, has_headers):
    return _wu.csv_reader_new(file, data_type, has_headers)
class Portfolio_(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    update = property(_wu.Portfolio__update_get, _wu.Portfolio__update_set)
    value = property(_wu.Portfolio__value_get, _wu.Portfolio__value_set)
    pnl = property(_wu.Portfolio__pnl_get, _wu.Portfolio__pnl_set)
    delete = property(_wu.Portfolio__delete_get, _wu.Portfolio__delete_set)

    def __init__(self):
        _wu.Portfolio__swiginit(self, _wu.new_Portfolio_())
    __swig_destroy__ = _wu.delete_Portfolio_

# Register Portfolio_ in _wu:
_wu.Portfolio__swigregister(Portfolio_)
class Position_(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    timestamp = property(_wu.Position__timestamp_get, _wu.Position__timestamp_set)
    quantity = property(_wu.Position__quantity_get, _wu.Position__quantity_set)
    price = property(_wu.Position__price_get, _wu.Position__price_set)
    active = property(_wu.Position__active_get, _wu.Position__active_set)

    def __init__(self):
        _wu.Position__swiginit(self, _wu.new_Position_())
    __swig_destroy__ = _wu.delete_Position_

# Register Position_ in _wu:
_wu.Position__swigregister(Position_)
class PositionVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    positions = property(_wu.PositionVector_positions_get, _wu.PositionVector_positions_set)
    active = property(_wu.PositionVector_active_get, _wu.PositionVector_active_set)
    count = property(_wu.PositionVector_count_get, _wu.PositionVector_count_set)
    capacity = property(_wu.PositionVector_capacity_get, _wu.PositionVector_capacity_set)
    add = property(_wu.PositionVector_add_get, _wu.PositionVector_add_set)
    remove = property(_wu.PositionVector_remove_get, _wu.PositionVector_remove_set)
    clear = property(_wu.PositionVector_clear_get, _wu.PositionVector_clear_set)
    get = property(_wu.PositionVector_get_get, _wu.PositionVector_get_set)
    total_quantity = property(_wu.PositionVector_total_quantity_get, _wu.PositionVector_total_quantity_set)
    delete = property(_wu.PositionVector_delete_get, _wu.PositionVector_delete_set)
    __swig_destroy__ = _wu.delete_PositionVector

    def __init__(self):
        _wu.PositionVector_swiginit(self, _wu.new_PositionVector())

# Register PositionVector in _wu:
_wu.PositionVector_swigregister(PositionVector)

def position_vector_new():
    return _wu.position_vector_new()
class PortfolioStats_(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    total_trades = property(_wu.PortfolioStats__total_trades_get, _wu.PortfolioStats__total_trades_set)
    winning_trades = property(_wu.PortfolioStats__winning_trades_get, _wu.PortfolioStats__winning_trades_set)
    losing_trades = property(_wu.PortfolioStats__losing_trades_get, _wu.PortfolioStats__losing_trades_set)
    stop_loss_exits = property(_wu.PortfolioStats__stop_loss_exits_get, _wu.PortfolioStats__stop_loss_exits_set)
    take_profit_exits = property(_wu.PortfolioStats__take_profit_exits_get, _wu.PortfolioStats__take_profit_exits_set)
    total_profit = property(_wu.PortfolioStats__total_profit_get, _wu.PortfolioStats__total_profit_set)
    total_loss = property(_wu.PortfolioStats__total_loss_get, _wu.PortfolioStats__total_loss_set)
    max_win = property(_wu.PortfolioStats__max_win_get, _wu.PortfolioStats__max_win_set)
    max_loss = property(_wu.PortfolioStats__max_loss_get, _wu.PortfolioStats__max_loss_set)
    record_trade = property(_wu.PortfolioStats__record_trade_get, _wu.PortfolioStats__record_trade_set)
    reset = property(_wu.PortfolioStats__reset_get, _wu.PortfolioStats__reset_set)
    delete = property(_wu.PortfolioStats__delete_get, _wu.PortfolioStats__delete_set)
    __swig_destroy__ = _wu.delete_PortfolioStats_

    def __init__(self):
        _wu.PortfolioStats__swiginit(self, _wu.new_PortfolioStats_())

# Register PortfolioStats_ in _wu:
_wu.PortfolioStats__swigregister(PortfolioStats_)

def portfolio_stats_new():
    return _wu.portfolio_stats_new()
class PositionSizingParams(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    size_type = property(_wu.PositionSizingParams_size_type_get, _wu.PositionSizingParams_size_type_set)
    size_value = property(_wu.PositionSizingParams_size_value_get, _wu.PositionSizingParams_size_value_set)

    def __init__(self):
        _wu.PositionSizingParams_swiginit(self, _wu.new_PositionSizingParams())
    __swig_destroy__ = _wu.delete_PositionSizingParams

# Register PositionSizingParams in _wu:
_wu.PositionSizingParams_swigregister(PositionSizingParams)
class SingleAssetPortfolioParams(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    initial_cash = property(_wu.SingleAssetPortfolioParams_initial_cash_get, _wu.SingleAssetPortfolioParams_initial_cash_set)
    tx_cost_pct = property(_wu.SingleAssetPortfolioParams_tx_cost_pct_get, _wu.SingleAssetPortfolioParams_tx_cost_pct_set)
    stop_loss_pct = property(_wu.SingleAssetPortfolioParams_stop_loss_pct_get, _wu.SingleAssetPortfolioParams_stop_loss_pct_set)
    take_profit_pct = property(_wu.SingleAssetPortfolioParams_take_profit_pct_get, _wu.SingleAssetPortfolioParams_take_profit_pct_set)
    slippage_pct = property(_wu.SingleAssetPortfolioParams_slippage_pct_get, _wu.SingleAssetPortfolioParams_slippage_pct_set)
    position_sizing = property(_wu.SingleAssetPortfolioParams_position_sizing_get, _wu.SingleAssetPortfolioParams_position_sizing_set)

    def __init__(self):
        _wu.SingleAssetPortfolioParams_swiginit(self, _wu.new_SingleAssetPortfolioParams())
    __swig_destroy__ = _wu.delete_SingleAssetPortfolioParams

# Register SingleAssetPortfolioParams in _wu:
_wu.SingleAssetPortfolioParams_swigregister(SingleAssetPortfolioParams)
class SingleAssetPortfolioTrack(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cash = property(_wu.SingleAssetPortfolioTrack_cash_get, _wu.SingleAssetPortfolioTrack_cash_set)
    positions = property(_wu.SingleAssetPortfolioTrack_positions_get, _wu.SingleAssetPortfolioTrack_positions_set)
    last_price = property(_wu.SingleAssetPortfolioTrack_last_price_get, _wu.SingleAssetPortfolioTrack_last_price_set)
    accum_expenses = property(_wu.SingleAssetPortfolioTrack_accum_expenses_get, _wu.SingleAssetPortfolioTrack_accum_expenses_set)
    stats = property(_wu.SingleAssetPortfolioTrack_stats_get, _wu.SingleAssetPortfolioTrack_stats_set)

    def __init__(self):
        _wu.SingleAssetPortfolioTrack_swiginit(self, _wu.new_SingleAssetPortfolioTrack())
    __swig_destroy__ = _wu.delete_SingleAssetPortfolioTrack

# Register SingleAssetPortfolioTrack in _wu:
_wu.SingleAssetPortfolioTrack_swigregister(SingleAssetPortfolioTrack)
class SingleAssetPortfolio_(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    base = property(_wu.SingleAssetPortfolio__base_get, _wu.SingleAssetPortfolio__base_set)
    params = property(_wu.SingleAssetPortfolio__params_get, _wu.SingleAssetPortfolio__params_set)
    track = property(_wu.SingleAssetPortfolio__track_get, _wu.SingleAssetPortfolio__track_set)

    def get_cash(self):
        return _wu.SingleAssetPortfolio__get_cash(self)

    def get_last_price(self):
        return _wu.SingleAssetPortfolio__get_last_price(self)

    def get_accum_expenses(self):
        return _wu.SingleAssetPortfolio__get_accum_expenses(self)

    def get_total_trades(self):
        return _wu.SingleAssetPortfolio__get_total_trades(self)

    def get_winning_trades(self):
        return _wu.SingleAssetPortfolio__get_winning_trades(self)

    def get_losing_trades(self):
        return _wu.SingleAssetPortfolio__get_losing_trades(self)

    def get_total_profit(self):
        return _wu.SingleAssetPortfolio__get_total_profit(self)

    def get_total_loss(self):
        return _wu.SingleAssetPortfolio__get_total_loss(self)

    def update(self, signal):
        return _wu.SingleAssetPortfolio__update(self, signal)

    def value(self):
        return _wu.SingleAssetPortfolio__value(self)

    def pnl(self):
        return _wu.SingleAssetPortfolio__pnl(self)
    __swig_destroy__ = _wu.delete_SingleAssetPortfolio_

    def __init__(self):
        _wu.SingleAssetPortfolio__swiginit(self, _wu.new_SingleAssetPortfolio_())

# Register SingleAssetPortfolio_ in _wu:
_wu.SingleAssetPortfolio__swigregister(SingleAssetPortfolio_)

def single_asset_portfolio_new(params):
    return _wu.single_asset_portfolio_new(params)
class Strategy_(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    update = property(_wu.Strategy__update_get, _wu.Strategy__update_set)
    delete = property(_wu.Strategy__delete_get, _wu.Strategy__delete_set)

    def __init__(self):
        _wu.Strategy__swiginit(self, _wu.new_Strategy_())
    __swig_destroy__ = _wu.delete_Strategy_

# Register Strategy_ in _wu:
_wu.Strategy__swigregister(Strategy_)
class CrossOverStrat_(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    base = property(_wu.CrossOverStrat__base_get, _wu.CrossOverStrat__base_set)
    short_ma = property(_wu.CrossOverStrat__short_ma_get, _wu.CrossOverStrat__short_ma_set)
    long_ma = property(_wu.CrossOverStrat__long_ma_get, _wu.CrossOverStrat__long_ma_set)
    threshold = property(_wu.CrossOverStrat__threshold_get, _wu.CrossOverStrat__threshold_set)
    last_signal = property(_wu.CrossOverStrat__last_signal_get, _wu.CrossOverStrat__last_signal_set)

    def update(self, data):
        return _wu.CrossOverStrat__update(self, data)
    __swig_destroy__ = _wu.delete_CrossOverStrat_

    def __init__(self):
        _wu.CrossOverStrat__swiginit(self, _wu.new_CrossOverStrat_())

# Register CrossOverStrat_ in _wu:
_wu.CrossOverStrat__swigregister(CrossOverStrat_)

def cross_over_strat_new(short_window, long_window, threshold):
    return _wu.cross_over_strat_new(short_window, long_window, threshold)
class Runner_(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    run = property(_wu.Runner__run_get, _wu.Runner__run_set)

    def __init__(self):
        _wu.Runner__swiginit(self, _wu.new_Runner_())
    __swig_destroy__ = _wu.delete_Runner_

# Register Runner_ in _wu:
_wu.Runner__swigregister(Runner_)
class BasicRunner_(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    portfolio = property(_wu.BasicRunner__portfolio_get, _wu.BasicRunner__portfolio_set)
    strategy = property(_wu.BasicRunner__strategy_get, _wu.BasicRunner__strategy_set)
    reader = property(_wu.BasicRunner__reader_get, _wu.BasicRunner__reader_set)

    def execute(self, verbose):
        return _wu.BasicRunner__execute(self, verbose)
    __swig_destroy__ = _wu.delete_BasicRunner_

    def __init__(self):
        _wu.BasicRunner__swiginit(self, _wu.new_BasicRunner_())

# Register BasicRunner_ in _wu:
_wu.BasicRunner__swigregister(BasicRunner_)

def basic_runner_new(portfolio, strategy, reader):
    return _wu.basic_runner_new(portfolio, strategy, reader)

def basic_runner_free(runner):
    return _wu.basic_runner_free(runner)

def wu_indicator_update(ind, value):
    return _wu.wu_indicator_update(ind, value)

def wu_indicator_value(ind):
    return _wu.wu_indicator_value(ind)

def strategy_call_update(strategy, data):
    return _wu.strategy_call_update(strategy, data)

def reader_call_next(reader):
    return _wu.reader_call_next(reader)

def portfolio_call_update(portfolio, signal):
    return _wu.portfolio_call_update(portfolio, signal)

def portfolio_call_value(portfolio):
    return _wu.portfolio_call_value(portfolio)

def portfolio_call_pnl(portfolio):
    return _wu.portfolio_call_pnl(portfolio)

def runner_call_run(runner, verbose):
    return _wu.runner_call_run(runner, verbose)

def csv_reader_open(filename, data_type, has_headers):
    return _wu.csv_reader_open(filename, data_type, has_headers)

# Version information
__version__ = '0.1.0'

# Alias to match C macro names
indicator_update = wu_indicator_update
indicator_value = wu_indicator_value

def create_signal(timestamp=0, side=SIDE_HOLD, price=0.0, quantity=0.0):
    """
    Create a Signal with the given parameters.

    Args:
        timestamp: Unix timestamp (default: 0)
        side: Signal side - SIDE_BUY, SIDE_SELL, or SIDE_HOLD (default: SIDE_HOLD)
        price: Execution price (default: 0.0)
        quantity: Quantity to trade (default: 0.0)

    Returns:
        Signal instance
    """
    return signal_init(timestamp, side, price, quantity)

def create_single_asset_portfolio(initial_cash=10000.0, tx_cost_pct=0.001, 
                                  stop_loss_pct=0.0, take_profit_pct=0.0,
                                  slippage_pct=0.0, size_type=POSITION_SIZE_ABS,
                                  size_value=1.0):
    """
    Create a SingleAssetPortfolio with the given parameters.

    Args:
        initial_cash: Initial cash amount (default: 10000.0)
        tx_cost_pct: Transaction cost percentage (default: 0.001)
        stop_loss_pct: Stop loss percentage (default: 0.0)
        take_profit_pct: Take profit percentage (default: 0.0)
        slippage_pct: Slippage percentage (default: 0.0)
        size_type: Position size type (POSITION_SIZE_ABS or POSITION_SIZE_PCT, default: POSITION_SIZE_ABS)
        size_value: Position size value (default: 1.0)

    Returns:
        SingleAssetPortfolio instance
    """
    params = SingleAssetPortfolioParams()
    params.initial_cash = initial_cash
    params.tx_cost_pct = tx_cost_pct
    params.stop_loss_pct = stop_loss_pct
    params.take_profit_pct = take_profit_pct
    params.slippage_pct = slippage_pct
    params.position_sizing.size_type = size_type
    params.position_sizing.size_value = size_value

    return single_asset_portfolio_new(params)

def open_csv_reader(filename, data_type=DATA_TYPE_CANDLE, has_headers=True):
    """
    Open a CSV file for reading market data.

    Args:
        filename: Path to CSV file
        data_type: Type of data (DATA_TYPE_CANDLE, DATA_TYPE_TRADE, or DATA_TYPE_SINGLE_VALUE)
        has_headers: Whether the CSV has headers (default: True)

    Returns:
        CsvReader instance or None on error
    """
    return csv_reader_open(filename, data_type, has_headers)

# Enable automatic memory management
# Objects will be automatically freed when garbage collected


